### ISSUE TITLE
Using a deprecated V2 Endpoint

### ISSUE THREAD

**Issue by dmcinnes** [heroku/heroku-apps#147]
Creating this issue to track the change.

Release info [uses a v2 endpoint to get a particular release's env vars](https://github.com/heroku/heroku-apps/blob/master/commands/releases/info.js#L33).

We now have a [v3 endpoint](https://devcenter.heroku.com/articles/platform-api-reference#config-vars-info-for-app-release) to support this.

/cc @dmathieu

**Comment by dmathieu** [comment]
@dmcinnes the command also uses the v2 endpoint to fetch the addons of a release.
I haven't dug into it yet. But I'm not sure that endpoint exists yet.

**Comment by dmcinnes** [comment]
@dmathieu ah missed that! We actually have that now too, added in https://github.com/heroku/api/pull/6732, under the field `addon_plan_names`.
