### ISSUE TITLE
ps quota should be of app owner not current user

### ISSUE THREAD

**Issue by dickeyxxx** [heroku/heroku-apps#158]
Right now we hit /account to get the account ID to use to get the quota for /account/{myid}/actions/get-quota.

This shows the right quota number if you are the same user as the owner, but if you are collaborating on someone else's app the quota is wrong.

Unsure if we have permission to view someone else's quota though, so it might be best to show the quota if the app is the same as the one you're collaborating on and nothing if not.

cc @calebthompson @dmcinnes

**Comment by dmcinnes** [comment]
The `get-quota` endpoint is run by [cedar-quota-manager](https://github.com/heroku/cedar-quota-manager) which doesn't appear to support general user requests, though I'm not sure how access is controlled.

**Comment by calebthompson** [comment]
In a perfect world, if the `/apps/:id` endpoint returned the quota, we could piggy back on the permissions checks for apps. That would also simplify the code somewhat and reduce number of API calls from the CLI for this command.

**Comment by ransombriggs** [comment]
@dmcinnes @dickeyxxx This was previously reported here https://github.com/heroku/cedar-ops/issues/3 and I cannot fix it until I have an endpoint that I can query for it.

**Comment by ransombriggs** [comment]
@dickeyxxx one option would be to just drop / tweak the output if the app owner does not match the requesting user, thoughts?

**Comment by dickeyxxx** [comment]
yeah like I proposed above? "...it might be best to show the quota if the app is the same as the one you're collaborating on and nothing if not."

**Comment by ransombriggs** [comment]
We no longer print the quota if the owner of app does not match the requesting account.
