### ISSUE TITLE
ps:stop without argument: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/heroku-apps#173]
Running `ps:stop` without an argument raises `Cannot read property 'indexOf' of undefined` instead of an error explaining that you need to say something like `ps:stop web` or `ps:stop web.1`. This can be a common mistake because other `ps` commands like `restart` do not require an argument.

Example:

```sh
$ heroku ps:stop
 ▸    Cannot read property 'indexOf' of undefined
```

**Comment by dickeyxxx** [comment]
@ryanbrainard what is the output of `heroku version`? I feel you might be on one of the stuck v6 releases because we fixed this bug

**Comment by ryanbrainard** [comment]
I was on `heroku-cli/6.6.0-6e58a42 beta (darwin-x64) node-v7.9.0`. I just completely uninstalled the CLI and reinstalled with `heroku-cli/6.6.7-ecf0119 (darwin-x64) node-v7.9.0` and it is working now:

```sh
$ heroku ps:stop
 ▸    Error: Missing required argument dyno
```

**Comment by dickeyxxx** [comment]
great! sorry about the trouble, neither the updating bug nor this should crop up again
