### ISSUE TITLE
Upgrade from heroku-apps 0.4.1 to 0.5.2 causes non-existant config variables to return 'undefined' in the shell

### ISSUE THREAD

**Issue by disdanes** [heroku/heroku-apps#19]
heroku-apps 0.4.1 behavior:
```
$ heroku config:get BLAH -a myapp

```
heroku-apps 0.5.2 behavior:
```
$ heroku config:get BLAH -a myapp
undefined
```
I think this is a fundamental change in the output of getting configuration variables, and has lots of consequences for commands that look at the output of configuration variables and is looking for the null vs the string 'undefined'. Was this a purposeful change or accidental ?

**Comment by dickeyxxx** [comment]
Intentional, but probably a bad idea. A fix should be in soon.

**Comment by ransombriggs** [comment]
This was fixed in #21 and should be live (I ran heroku update & verified)

**Comment by dahoste** [comment]
Thanks!

**Comment by disdanes** [comment]
Thanks for the quick turnaround!
