### ISSUE TITLE
runningRelease resolution logic flawed

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/heroku-apps#192]
This [code](https://github.com/heroku/heroku-apps/blame/bac7045dd08faa547f122bf6d16a5e74ae3cdbc7/src/commands/releases/index.js#L37) determines this `runningRelease`:

```js
let runningRelease = releases.filter((r) => r.status === 'pending').slice(-1)[0]
```

This logic depends on how many and which other releases are in `releases`. For example, in the example below, if there are 29 releases, the last two are `pending` (in JSON), so they are displayed the user as v289 being `pending` and v289 being `release command executing`.

```term
$ heroku releases -a redacted-app -n 29
=== redacted-app Releases - Current: v316
...
v289  Set REDACTED1 config vars pending              user@salesforce.com           2017/08/24 03:20:03 +0900
v288  Set REDACTED2 config vars release command executing  user@salesforce.com           2017/08/24 03:19:52 +0900
```

However, by only fetching 28 releases, v289 changes to `release command executing` because it is now considered the `runningRelease`:

```term
$ heroku releases -a redacted-app -n 29
=== redacted-app Releases - Current: v316
...
v289  Set REDACTED1 config vars release command executing              user@salesforce.com           2017/08/24 03:20:03 +0900
```

In addition to this problem, it is questionable why the last release is considered the `runningRelease` at all. Shouldn't API be getting this information from the runtimes? I don't see how the CLI would be able to determine this on it's own.

**Comment by dmathieu** [comment]
We added this logic a year ago, when we started work on preventing releases from running concurrently, but that work was canceled.

@jbyrum what do you think of always showing "pending" and never "release command executing"?
cc @heroku/build

**Comment by jbyrum** [comment]
@dmathieu I think we need to discuss this one in person.  Can we talk in our weekly build meeting?

**Comment by dmathieu** [comment]
We're going to be fixing this so always show "release command executing", and go back to the drawing board for preventing releases from running concurrently.
