### ISSUE TITLE
About deply rails and modify nodejs version

### ISSUE THREAD

**Issue by unixc3t** [heroku/heroku-apps#199]
my rails app  use the javascript es6 syntax,  i found default install nodejs v6 ,

I saw your doc   , the url is  https://devcenter.heroku.com/articles/ruby-support#installed-binaries

------------
Once you have done this you’ll need a package.json file in the root of your app. For example to install version 6.2.2 your package.json could look like this: { "engines" : { "node": "6.2.2" } }

Commit to git:

$ git add pacakage.json

$ git commit -m 'specify node version'

Now the next time you deploy your Ruby application will use Node version 6.2.2.

------------------

I modiy package.json file with

{ "name": "shopa", "private": true, "dependencies": {}, "engines": { "node": "8.5.0" } }

but i push it  , it  still  nodejs v6 

because I am a free user? I can't modify nodejs version?

**Comment by jdxcode** [comment]
you should submit a support ticket, this is a project for the Heroku CLI only
