### ISSUE TITLE
apps:info serializes a pipeline-coupling as the pipeline key

### ISSUE THREAD

**Issue by raulb** [heroku/heroku-apps#206]
If you look at the serialization of `heroku apps:info APP --json`, you may think the serialization is confusing.

e.g.:

```
> heroku apps:info APP --json
   ...
  "pipeline": {
    "created_at": "2016-11-23T14:32:18+00:00",
    "app": {
      "id": APP_ID
    },
    "id": PIPELINE_COUPLING_ID,
    "pipeline": {
      "id": PIPELINE_ID,
      "name": "kolkrabbi"
    },
    "stage": "staging",
    "updated_at": "2016-11-23T14:32:18+00:00"
  }
}
```

Notice there is a pipeline nested in the main `pipeline` key. I personally think this is confusing, and I'd recommend changing the main `pipeline` key to `pipeline_coupling` instead.

**Comment by jdxcode** [comment]
Sounds good to me, I actually thought about doing this originally. We don’t have a great migration story though if anyone is currently depending on this behavior.

I’m gonna be out this week, but let me think about what we should do for migration before we merge your PR
